### ISSUE TITLE
Check Box Groups

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-elements#2]
Allow the ability to add multiple check boxes with one control. Must include an optional "check all / uncheck all" link at the top above the first checkbox.

**Comment by tdondich** [comment]
Marking as won't do for initial release. This can be done by the implementing product that uses these form controls.  Otherwise, this makes assumptions of where the check all /uncheck all should be, etc.

If we want to do this again in the future, we can re-open with more concrete spec.
